name: 'dbt_core'
version: '1.0.0'

query-comment:
  comment: "snowflake_dagster_dbt_v1_opaque_id[[[{{ node.unique_id }}:{{ invocation_id }}]]]"
  append: true

profile: 'dbt'

model-paths: ["models", "groups"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

dispatch:
  - macro_namespace: dbt
    search_order: ['dbt_core', 'dbt_snowflake', 'dbt']


clean-targets:
  - "target"
  - "dbt_packages"
models:
  +persist_docs:
    relation: true
    columns: true
  dbt_core:
    +group: data_foundation

    staging:
      +group: data_foundation

    intermediate:
      int_marketing:
        +group: marketing

    marts:
      mrt_marketing:
        +group: marketing

tests:
  dbt_core:
    +group: data_foundation

seeds:
  +persist_docs:
    relation: true
    columns: true
  dbt_core:
    +group: data_foundation

    mrt_marketing:
      +group: marketing

snapshots:
  +persist_docs:
      relation: true
      columns: true
  dbt_core:
    +group: data_foundation
flags:
  require_generic_test_arguments_property: true