dbt:
  outputs:
    prod:
      account: "{{ env_var('DESTINATION__SNOWFLAKE__HOST', '') }}"
      user: "{{ env_var('DESTINATION__SNOWFLAKE__USER', '') }}"
      password: "{{ env_var('DESTINATION__SNOWFLAKE__PASSWORD', '') }}"
      role: "{{ env_var('DESTINATION__SNOWFLAKE__ROLE', '') }}"
      database: analytics
      schema: prod
      threads: 8
      type: snowflake
      warehouse: compute_wh
    qa:
      account: "{{ env_var('DESTINATION__SNOWFLAKE__HOST', '') }}"
      user: "{{ env_var('DESTINATION__SNOWFLAKE__USER', '') }}"
      password: "{{ env_var('DESTINATION__SNOWFLAKE__PASSWORD', '') }}"
      role: "{{ env_var('DESTINATION__SNOWFLAKE__ROLE', '') }}"
      database: _qa_analytics
      schema: qa
      threads: 8
      type: snowflake
      warehouse: compute_wh
    dev:
      account: "{{ env_var('DESTINATION__SNOWFLAKE__HOST', '') }}"
      user: "{{ env_var('DESTINATION__SNOWFLAKE__USER', '') }}"
      password: "{{ env_var('DESTINATION__SNOWFLAKE__PASSWORD', '') }}"
      role: "{{ env_var('DESTINATION__SNOWFLAKE__ROLE', '') }}"
      database: _dev_analytics
      schema: "{{ env_var('DESTINATION__SNOWFLAKE__USER', '') }}"
      threads: 1
      type: snowflake
      warehouse: compute_wh

  target: "{{ env_var('TARGET', 'dev') }}"