[project]
name = "data_foundation"
version = "0.1.0"
description = "Code location for dagster that exposes dbt, sling, and dlt resources for Analytics Engineering"
requires-python = ">=3.12, <3.13"
dependencies = [
    "dagster-cloud==1.11.12",
    "dagster-dbt==0.27.12",
    "dagster-dlt==0.27.12",
    "dagster-k8s==0.27.12",
    "dagster-postgres==0.27.12",
    "dagster-sling==0.27.12",
    "dagster-snowflake==0.27.12",
    "data-platform-utils",
    "pandas>=2.3.3",
    "psutil==7.1.0",
]

[tool.uv.sources]
data-platform-utils = { path = "../../libs/data_platform_utils" }

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "data_foundation.definitions"
code_location_name = "data_foundation"

[tool.dg]
directory_type = "project"
project.root_module = "data_foundation"
