site_name: Data Platform
theme:
  name: "readthedocs"

docs_dir: "docs\\docs"
site_dir: "docs\\site"

theme:
  name: material

plugins:
  - search
  - mkdocstrings
  - gen-files:
      scripts:
      - docs/gen_doc_stubs.py
  - mermaid2:
      javascript: https://unpkg.com/mermaid/dist/mermaid.min.js