# Connection profiles that tell dbt how to talk to Snowflake in each environment.
# Platform engineers should manage account/warehouse defaults here, while data
# engineers primarily switch the TARGET environment variable when running locally.
dbt:
  outputs:
    prod:
      # Production analytics role used by scheduled Dagster jobs.
      database: analytics
      schema: prod
      account: "{{ env_var('DESTINATION__HOST') }}"
      role: "{{ env_var('DESTINATION__ROLE') }}"
      user: "{{ env_var('DESTINATION__USER') }}"
      password: "{{ env_var('DESTINATION__PASSWORD') }}"
      warehouse: "{{ env_var('DESTINATION__WAREHOUSE') }}"
      threads: 8
      type: snowflake
    dev:
      # Developer sandbox settings for local iteration.
      database: _dev_analytics
      schema: "{{ env_var('DESTINATION__USER') }}"
      account: "{{ env_var('DESTINATION__HOST') }}"
      role: "{{ env_var('DESTINATION__ROLE') }}"
      user: "{{ env_var('DESTINATION__USER') }}"
      password: "{{ env_var('DESTINATION__PASSWORD') }}"
      warehouse: "{{ env_var('DESTINATION__WAREHOUSE') }}"
      threads: 1
      type: snowflake

  # Default target can be overridden via TARGET environment variable.
  target: "{{ env_var('TARGET', 'dev') }}"