resources:
    google_ads.campaigns:
        entry: data.google_ads
        arguments: [get_campaigns]
        primary_key: id
        write_disposition: merge
        kinds: {api}

    google_ads.criterion:
        entry: data.google_ads
        arguments: [get_criterion]
        primary_key: id
        write_disposition: merge
        kinds: {api}

sources:
    google_ads:
        resources: [google_ads.campaigns, google_ads.criterion]
        parallelized: true
        meta:
            dagster:
                automation_condition: on_schedule
                automation_condition_config:
                    cron_schedule: "@daily"
                    cron_timezone: utc
                freshness_lower_bound_delta_seconds: 108000