connections:
  - name: accounts_db
    type: postgres
    database: {SOURCE__ACCOUNTS_DB__DATABASE: show}
    host: {SOURCE__ACCOUNTS_DB__HOST: show}
    port: {SOURCE__ACCOUNTS_DB__PORT: mask}
    user: {SOURCE__ACCOUNTS_DB__USER: mask}
    password: {SOURCE__ACCOUNTS_DB__PASSWORD: mask}

replications:
  - name: accounts_db->snowflake
    env: {SLING_LOADED_AT_COLUMN: timestamp}
    source: accounts_db
    target: snowflake
    defaults:
      mode: incremental
      object: '{stream_schema_upper}.{stream_table_upper}'
      primary_key: [id]
      update_key: updated_at
      target_options:
        column_casing: snake
        add_new_columns: true
        adjust_column_type: true
      meta:
        dagster:
          automation_condition: "on_cron_no_deps"
          automation_condition_config: {"cron_schedule":"@daily", "cron_timezone":"utc"}
          freshness_check: {"lower_bound_delta_seconds": 129600}
    streams:
      accounts_db.accounts: {"meta": {"dagster": {"tags": ['contains_pii', 'my_tag']}}}
