resources:
    facebook_ads.campaigns:
        entry: data.get_campaigns
        primary_key: id
        write_disposition: merge
        kinds: {api}

sources:
    facebook_ads:
        resources: [facebook_ads.campaigns]
        parallelized: true
        meta:
            dagster:
                automation_condition: on_schedule
                automation_condition_config:
                    cron_schedule: "@daily"
                    cron_timezone: utc
                freshness_lower_bound_delta_seconds: 108000
