# MkDocs configuration for building the developer documentation site. Platform
# engineers can tweak theme/plugins here while data engineers can add new docs by
# extending the navigation under docs/.
site_name: Data Platform
theme:
  name: "readthedocs"

# The repo uses Windows-style paths in mkdocs.yml to support GitHub Pages builds on
# Windows runners. Update both docs_dir and site_dir together if you reorganize docs.
docs_dir: "./docs"
site_dir: "./site"

theme:
  # We use Material for MkDocs to unlock advanced navigation and search features.
  name: material

plugins:
  - search # Standard full-text search across generated pages.
  - mkdocstrings: # Autodoc support for Python objects referenced in the docs/ tree.
      handlers:
        python:
          paths: 
            - ../packages/data_foundation/src
            - ../packages/data_science/src
            - ../libs/analytics_utils/src
            - ../libs/data_platform_utils/src
  - mermaid2: # Enable Mermaid diagrams in Markdown files for architecture documentation.
      javascript: https://unpkg.com/mermaid/dist/mermaid.min.js