[project]
name = "data_analytics"
version = "0.1.0"
description = "Environment for interactive analysis of data stored in snowflake"
readme = "README.md"
requires-python = "==3.10.*"
dependencies = [
    "analytics-utils",
    "faker>=37.11.0",
    "ipykernel>=6.30.1",
    "snowflake-ml-python>=1.16.0",
    "ruff",
    "sqlfluff"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.uv.sources]
analytics-utils = { path = "../../libs/analytics_utils" }

[tool.ruff]
line-length = 88

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 20
quote-style = "double"
indent-style = "space"
[tool.ruff.lint]
select = [
    "E", # pycodestyle
    "F", # Pyflakes
    "UP", # pyupgrade
    "B",  # flake8-bugbear
    "SIM", # flake8-simplify
    "I", # isort
]

[tool.sqlfluff]
core.exclude_rules = ["AL07", "RF02", "ST06"]
core.max_line_length = 88
core.dialect = "snowflake"
indentation.tab_space_size = 4
layout.type.alias_expression.spacing_before = "align"
layout.type.alias_expression.align_within = "select_clause"
rules.aliasing.table.aliasing = "implicit"
rules.aliasing.column.aliasing = "implicit"
