import unittest

# from unittest.mock import patch


class TestFactory(unittest.TestCase): ...

class TestBuildDefinitions(TestFactory): ...
class TestParseConnections(TestFactory): ...
class TestCreateResource(TestFactory): ...
class TestParseReplication(TestFactory): ...
class TestCreateAsset(TestFactory): ...
class TestSetSchema(TestFactory): ...
class TestGetSlingDeps(TestFactory): ...
class TestGetFreshnessChecks(TestFactory): ...


if __name__ == "__main__":
    unittest.main()