import unittest

# from unittest.mock import patch


class TestTranslator(unittest.TestCase): ...

class TestGetAssetSpec(TestTranslator): ...
class TestGetAssetKey(TestTranslator): ...
class TestGetDepsAssetKey(TestTranslator): ...
class TestGroupName(TestTranslator): ...
class TestGetTags(TestTranslator): ...
class TestGetAutomationCondition(TestTranslator): ...
class TestGetPartitionsDef(TestTranslator): ...


if __name__ == "__main__":
    unittest.main()