# Workflow for running python checks on data science package
name: Data Science Python Checks

on:
  pull_request:
    types:
      - opened
    branches:
      - "main"
      - "dev"
    paths:
      - "/data_science/**/*.py"

permissions:
  checks: write
  contents: read

jobs:
  python_linting:
    environment:
      name: data_science
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Ruff Check
        working-directory: ./data_foundation
        run: uv run ruff check