# Workflow for running python checks on data foundation package
name: Data Foundation Python Checks

on:
  pull_request:
    branches:
      - "main"
      - "dev"
    paths:
      - "/data_foundation/**/*.py"

permissions:
  contents: read

jobs:
  python_checks:
    environment:
      name: data_foundation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Ruff Check
        working-directory: ./data_foundation
        run: uv run ruff check