# Workflow for running linting checks on data foundation package
name: Linting

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "main"
      - "qa"

permissions:
  checks: write
  contents: read

jobs:
  sql_linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: SQLFluff Check
        run: uv run --only-group sqlfluff sqlfluff lint --format github-annotation-native

  python_linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Ruff Check
        run: uv run --only-group ruff ruff check --output-format github

