# Workflow for running linting checks on data foundation package
name: Unit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "main"
      - "qa"

permissions:
  checks: write
  contents: read

jobs:

  pytest_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Sync Packages
        run: uv sync --all-packages

      - name: Pytest Check
        run: uv run pytest

